# Generated by Django 4.2.16 on 2024-12-12 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task_dashboard', '0002_alter_task_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.IntegerField(choices=[(0, 'Not Started'), (1, 'In Progress'), (2, 'Completed'), (3, 'Overdue')], default=0),
        ),
    ]
